### ISSUE TITLE
支持把 bookmarks 重新分组吗？

### ISSUE THREAD

**Issue by rydensun** [Pintree-io/pintree#1]
把文件夹里面所有的书签都分析一遍，然后重新建立文件夹并放到对应的文件夹中

**Comment by ViggoZ** [comment]
> 把文件夹里面所有的书签都分析一遍，然后重新建立文件夹并放到对应的文件夹中

这个功能在规划当中，其他功能建议和开发情况可以在 [pintree.canny.io](https://pintree.canny.io/) 这里查看
