### ISSUE TITLE
建议:chrome 书签 互转

### ISSUE THREAD

**Issue by zchdoc** [Pintree-io/pintree#12]
和chrome 书签 互转 
现在可以从chrome 导出书签到 pintree
但是不能从pintree生成chrome 书签并导入 chrome，添加修改同步书签有点麻烦 
对于多台设备书签重度用户，这个同步功能是个痛点 就算是单独的chrome同步也是，
希望能添加 互转 和 书签的编辑功能

**Comment by werner-balonius** [comment]
+1，多设备支持和同步这个功能很有必要

**Comment by markyun** [comment]
+1， 不然和 chrome 书签  对比，好像并没有什么优势。

**Comment by xkloveme** [comment]
为啥不直接做成浏览器插件
替换主页

**Comment by JerryYang-30** [comment]
> 和chrome 书签 互转 现在可以从chrome 导出书签到 pintree 但是不能从pintree生成chrome 书签并导入 chrome，添加修改同步书签有点麻烦 对于多台设备书签重度用户，这个同步功能是个痛点 就算是单独的chrome同步也是， 希望能添加 互转 和 书签的编辑功能

你描述的这个同步功能好像就是floccus bookmarks sync（不过floccus没有pintree这么好看的界面）

**Comment by zchdoc** [comment]
> 为啥不直接做成浏览器插件 替换主页

书签太多了 几千个  😳

**Comment by zchdoc** [comment]
> floccus bookmarks sync

类似得插件挺多的，各有利弊吧，以前也用过不少，不过我最近写了几行代码，单向的从chrome 导入到 pintree文件夹，然后提交 json文件就行了  不用手动导入了，多浏览器也可以下载覆盖chrmoe数据文件夹的 bookmark json文件   先简单对付一下。。。
