### ISSUE TITLE
logo大面积失效,https://logo.clearbit.com/xxx支持的很少

### ISSUE THREAD

**Issue by SAnBlog** [Pintree-io/pintree#13]
本地局域网的服务书签全部挂了,公开的网站有一半的logo也无法显示,请提供多种logo访问方式

**Comment by ViggoZ** [comment]
已经优化书签图标不显示的问题，如果没有拿到书签图标则显示默认图标。

关于你的问题，我们弃用了本地favicon的方式，因为考虑到如果保留本地base64图标到json文件中，json文件则会过大。

如果你想保留本地书签，可以考虑继续导出浏览器书签的html文件，然后使用官网的 [json-converter](https://pintree.io/json-converter.html)工具转换为json文件，这样会保留本地局域网书签的图标。

**Comment by SAnBlog** [comment]
> 已经优化书签图标不显示的问题，如果没有拿到书签图标则显示默认图标。
> 
> 关于你的问题，我们弃用了本地favicon的方式，因为考虑到如果保留本地base64图标到json文件中，json文件则会过大。
> 
> 如果你想保留本地书签，可以考虑继续导出浏览器书签的html文件，然后使用官网的 [json-converter](https://pintree.io/json-converter.html)工具转换为json文件，这样会保留本地局域网书签的图标。

可以,这看着舒服多了
