### ISSUE TITLE
Add default theme according to the system

### ISSUE THREAD

**Issue by andre-rd-rodrigues** [Pintree-io/pintree#15]
## Overview:
Pintree currently requires users to manually switch between light and dark themes. To enhance user experience and align with modern software practices, Pintree should automatically adjust its theme according to the system theme settings.

## Problem:
Users who prefer their applications to match their system theme settings find it inconvenient to manually switch themes in Pintree. This lack of synchronization can lead to a disjointed user experience, especially for those who frequently toggle between light and dark modes on their devices.

## Proposed Solution:
Implement a feature that allows Pintree to detect and apply the system theme automatically. This feature should include:

- System Theme Detection: Use appropriate APIs (e.g `window.matchMedia("(prefers-color-scheme: light)")`) to detect the current system theme (light or dark)
- Automatic Theme Application: Automatically switch Pintree’s theme to match the system theme upon startup and whenever the system theme changes.

## Benefits:

1. Enhanced User Experience: Users enjoy a seamless and consistent visual experience across all applications.
2. Accessibility: Improves accessibility for users with visual impairments or those who require specific contrast settings.
3. Modernization: Keeps Pintree up-to-date with contemporary software standards, which commonly include system theme synchronization.

**Comment by ViggoZ** [comment]
Thank you for your contribution.
