### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by mrdong916** [Pintree-io/pintree#17]
有没有考虑过直接做进插件里，然后自动读取浏览器的书签生成界面信息，省去了导出和导入的步骤

**Comment by ViggoZ** [comment]
> 有没有考虑过直接做进插件里，然后自动读取浏览器的书签生成界面信息，省去了导出和导入的步骤

Pintree目前的定位是分享自己的书签到公网，而不是在本地管理书签，本地管理书签这个可以等后期我们做线上托管的版本就会有。
