### ISSUE TITLE
本地没法访问吗？

### ISSUE THREAD

**Issue by Ronaldoshuang** [Pintree-io/pintree#2]

**Comment by TaiYouWeb** [comment]
到官网根据系统安装 node.js 环境。

安装完毕后执行：
`npm install -g http-server
`http-server '此处填写项目目录例如：D:\pintree\' -p 12345
`
然后访问 localhost:12345 即可。

node 以及 http-server安好以后：
如果是windows，新建一个记事本，将后缀改为.bat，将以下代码修改后贴上，双击即可执行。

`
@echo off
cd /d D:\pintree
start http-server D:\pintree\ -p 12345
start http://localhost:12345
`

**Comment by Ronaldoshuang** [comment]
OK，谢谢
