### ISSUE TITLE
希望按照原始顺序排列书签和文件夹

### ISSUE THREAD

**Issue by hondaya06** [Pintree-io/pintree#22]
现在文件夹在书签前面，并且书签顺序是乱套的。
另外希望手机端网页支持返回手势，谢谢。

**Comment by ErrorRua** [comment]
https://github.com/Pintree-io/pintree/blob/425a5a77c228e622be76af2066665759d81c0287/index.html#L559
把sort排序给删了就是书签导入的顺序了

**Comment by ViggoZ** [comment]
> 现在文件夹在书签前面，并且书签顺序是乱套的。 另外希望手机端网页支持返回手势，谢谢。

已经修改为默认排序
