### ISSUE TITLE
请问如何设置仅自己可见 How do I set this to be visible only to myself?

### ISSUE THREAD

**Issue by zyoung1212** [Pintree-io/pintree#25]
请问如何设置仅自己可见 How do I set this to be visible only to myself?

**Comment by ir3ne** [comment]
@zyoung1212 are you talking about permissions?

**Comment by BlackSpacee** [comment]
> 请问如何设置仅自己可见 How do I set this to be visible only to myself?

我也想说，这样的话比较隐私的书签就会明文暴露在项目文件夹

I also want to say that such bookmarks with sensitive information will be exposed in plain text in the project folder.

**Comment by ErrorRua** [comment]
把代码拉下来自己跑不就好了

**Comment by mxlt02** [comment]
部署在自己电脑上
